name: Test Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  print_success:
    name: Print Success Status
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - run: echo "SUCCEEDED"


